#SEO Tagging [jekyll-seo-tag]
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until the next configuration section
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# favicon: /favicon.ico

twitter:
  username: jekyllrb
  card: summary

#Social [jekyll-seo-tag]
# social:
#   name: jekyll
#   links:
#     - https://twitter.com/jekyllrb
#     - https://www.facebook.com/jekyllrb
#     - https://www.linkedin.com/in/parkr
#     - https://plus.google.com/+jekyll
#     - https://github.com/jekyll
#     - https://keybase.io/jekyllrb

#blog features
show_excerpts: true # set to true to show excerpts on the homepage

#Google Analytics
google_analytics: UA-NNNNNNNN-N

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: parkr
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - name : about.md
    title : About Page
    url : /yaght-demo/about
  - name : changelog.md
    title : Changelog
    url : /yaght-demo/changelog
  - name : external.md
    title : External Page
    url : https://jekyllrb.com/

# blog settings
permalink: "/blog/:year/:month/:day/:title"
# paginate: 20
# paginate_path: "/blog/page:num/"


# technical settings
baseurl: "/yaght-demo" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: chrishasz/yaght